name: 更新股债利差与巴菲特指标图表

on:
  schedule:
    # 每天北京时间 09:00 (UTC 01:00)
    - cron: '0 1 * * *'
    # 每天北京时间 16:00 (UTC 08:00)  
    - cron: '0 8 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-charts:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 配置中文字体
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk
        fc-cache -fv
        
    - name: 生成股债利差图表和数据
      run: python 国债利差均线.py
        
    - name: 生成巴菲特指标图表和数据
      run: python 巴菲特指标可视化图表.py
      
    - name: 生成AI市场分析
      run: python AKShareSummer.py
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        
    - name: 提交更新的图表和分析
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.png *.csv *.json *.md
        git diff --staged --quiet || git commit -m "自动更新图表和AI分析 - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
